services:
  synapse:
    image: matrixdotorg/synapse:v1.127.0
    container_name: synapse
    restart: unless-stopped
    environment:
      - SYNAPSE_SERVER_NAME=${SYNAPSE_SERVER_NAME}
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_DIR=/data
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_DATA_DIR=/data
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
    volumes:
      - ./synapse-data:/data
    depends_on:
      - postgres
    networks:
      - internal
      - default

  postgres:
    image: postgres:16.3-alpine
    container_name: synapse_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - internal

  element-web:
    image: vectorim/element-web:v1.11.96
    container_name: element-web
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8081:80"
      - "4443:443"
    environment:
      - MATRIX_SUBDOMAIN=${MATRIX_SUBDOMAIN}
      - ELEMENT_SUBDOMAIN=${ELEMENT_SUBDOMAIN}
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - synapse
      - element-web
    networks:
      - default

networks:
  internal:
    internal: true
  default:
